#!/usr/bin/env node
// Seed a deterministic Surveyor baseline for Niro and write the generated
// credential catalog and fixture references the run consumes.
//
//   node niro/harness/seed.mjs --base http://127.0.0.1:8788 --config-dir <dir>
//
// Two original submissions are created through the public intake API
// (challenge -> proof of work -> create -> answers). Each gets a distinct
// access code, which is a real target credential for the resume/addendum
// routes. Secrets are written only to credentials.yaml (gitignored).

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { solvePow } from "../../dist/smoke-lib.js";

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const base = arg("--base", "http://127.0.0.1:8788").replace(/\/+$/, "");
const configDir = arg("--config-dir", new URL("..", import.meta.url).pathname);

const SUBMITTERS = [
  {
    id: "SUBMITTER_A",
    answers: [
      {
        q: "How are rosters set, and what happens when you push back?",
        topic: "roster",
        value:
          "Rosters are posted every second Thursday. Swaps are agreed between crews and only rejected when coverage drops below two. Pushing back to the planner usually results in a call, then a written change.",
      },
      {
        q: "Describe a time safety and speed were in conflict.",
        topic: "safety",
        value:
          "A load was late and the crew was asked to skip the pre-start check. The supervisor signed off instead and the run went ahead; nothing failed that night, but the checklist was marked complete without being done.",
      },
      {
        q: "How does pay actually work — penalties, overtime, allowances?",
        topic: "pay",
        value:
          "Night shift attracts a penalty from 10pm, and the travel allowance only appears when the depot allocates it. On paper the rules are clear; in practice the allowance code is chosen by the roster clerk.",
      },
    ],
  },
  {
    id: "SUBMITTER_B",
    answers: [
      {
        q: "What do your hours do to sleep, family, and health?",
        topic: "hours",
        value:
          "Two weeks of nights followed by four days off. The first off day is spent asleep and the fourth is spent dreading the return. Most of the crew trade the fourth day for overtime when it is offered.",
      },
      {
        q: "How does management respond to complaints?",
        topic: "management",
        value:
          "Complaints go to the area manager, who forwards them to the same supervisor the complaint is about. Follow-ups are answered by email quoting the procedure rather than addressing the event.",
      },
    ],
  },
];

async function createSubmission(sender) {
  const challenge = await (await fetch(`${base}/api/intake/challenge`)).json();
  const nonce = await solvePow(challenge.challenge, challenge.difficulty);
  const created = await (
    await fetch(`${base}/api/intake`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ pow: { challenge: challenge.challenge, nonce } }),
    })
  ).json();
  if (!created.access_code) {
    throw new Error(`intake create failed for ${sender.id}: ${JSON.stringify(created)}`);
  }
  const steps = await fetch(`${base}/api/intake/${created.id}/steps`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      answers: sender.answers,
      access_code: created.access_code,
    }),
  });
  if (!steps.ok) {
    throw new Error(`steps failed for ${sender.id}: HTTP ${steps.status}`);
  }
  return { credentialId: sender.id, id: created.id, code: created.access_code };
}

function yamlString(value) {
  return `"${String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function writeCredentials(rows) {
  const lines = [
    "# Generated by niro/harness/seed.sh — do not commit.",
    "# Throwaway local test identities for the Niro-started checkout runtime.",
    "credentials:",
    "  - credential_id: OPERATOR",
    '    description: "Operator bearer token for the local Surveyor app. Send it as the Authorization header value (Niro sends the secret verbatim; the app also accepts an optional `Bearer ` prefix). Every operator-gated route accepts it: /api/corpus, /api/telemetry, /api/audit/ciphertext, and the operator actions under /api/engine and /api/reports. This is a throwaway token for the local run, not a deployed installation."',
    "    type: bearer_token",
    `    secret: ${yamlString("test-op-token")}`,
  ];
  for (const row of rows) {
    lines.push(
      `  - credential_id: ${row.credentialId}`,
      `    description: ${yamlString(
        `Access code for seeded original submission ${row.id}. The code has no header or cookie: POST /api/intake/resume with JSON body {"access_code": "<secret>"} returns the submission id, and POST /api/intake/${row.id}/addendum with body {"access_code": "<secret>", "pow": {...}} creates an addendum child. The same code is the source's identity in the public survey UI. Pair with the other SUBMITTER code to verify one submitter cannot resume or amend the other's submission.`,
      )}`,
      "    type: static_token",
      `    secret: ${yamlString(row.code)}`,
    );
  }
  writeFileSync(join(configDir, "credentials.yaml"), lines.join("\n") + "\n");
}

function writeFixtures(rows) {
  const lines = [
    "# Generated by niro/harness/seed.sh — do not commit.",
    "fixtures:",
    "  - name: target_url",
    '    description: "Base URL of the app started by niro/harness/start.sh."',
    `    value: ${yamlString(base)}`,
  ];
  for (const row of rows) {
    lines.push(
      `  - name: ${row.credentialId.toLowerCase()}_submission`,
      `    description: ${yamlString(
        `UUID of seeded original submission ${row.id}. Use it for the step, attachment, addendum, and rounds routes; the matching access code is the ${row.credentialId} credential.`,
      )}`,
      `    value: ${yamlString(row.id)}`,
    );
  }
  lines.push(
    "  - name: corpus_drain_operator_route",
    '    description: "Operator drain for manually held attachments on a submission."',
    `    value: ${yamlString("POST " + base + "/api/intake/<submission-id>/attachments/drain")}`,
  );
  writeFileSync(join(configDir, "fixtures.yaml"), lines.join("\n") + "\n");
}

const rows = [];
for (const sender of SUBMITTERS) {
  rows.push(await createSubmission(sender));
}
writeCredentials(rows);
writeFixtures(rows);
console.log(
  `seed: ${rows.length} submissions ready (${rows.map((r) => r.id).join(", ")}); wrote credentials.yaml and fixtures.yaml`,
);
