#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# The trial runs from the repo root, and its working values live in a
# gitignored session file — never in the repo, never in a commit.
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE=".env.live-trial"
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"
TRIAL_DATE="$(date +%F)"
EVIDENCE_DIR="evidence/live-trial"
EVIDENCE_FILE="$EVIDENCE_DIR/$TRIAL_DATE-provisioning-trial.md"
mkdir -p "$EVIDENCE_DIR"

# Wrangler helper, defined once so every stage (deploy, OAuth re-deploy)
# uses it — including when the deploy-button path skipped the build stage.
# Wrangler 4 prefers CLOUDFLARE_ACCOUNT_ID and prints a deprecation notice
# for CF_ACCOUNT_ID that would poison JSON parsing: every wrangler call
# runs with the old name hidden.
wr() { env -u CF_ACCOUNT_ID CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" npx wrangler "$@"; }
# Parse wrangler JSON from the first [ or { — notices and banners on
# stdout must never break id extraction.
parse_uuid() {
  node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{const j=JSON.parse(s.slice(s.search(/[[{]/)));if(j&&typeof j==="object"&&!Array.isArray(j)&&(j.uuid||j.database_id)){console.log(j.uuid||j.database_id);return}const a=Array.isArray(j)?j:(j.d1_databases||j.databases||[]);const h=a.find(d=>d.name==="surveyor-db");console.log(h?(h.uuid||h.database_id):"")}catch(e){}})'
}

banner "Surveyor live trial (A16 #17 · A17 #18)"

# ── Stage 1: prerequisites ───────────────────────────────────────────────
stage "Prerequisites"
say "This trial deploys Surveyor to your own Cloudflare account, boots it,"
say "exercises the live provisioner and consent flow, runs the deployed"
say "smoke, then tears everything down. You need a Cloudflare account."
for cmd in node npm npx curl; do
  command -v "$cmd" >/dev/null 2>&1 || { warn "missing required command: $cmd"; exit 1; }
done
say "node $(node --version), npm and curl are present."
if ! node -e "process.exit(process.versions.node.split('.')[0] >= 22 ? 0 : 1)"; then
  warn "node 22+ is required (package.json engines)."
  exit 1
fi
note "wrangler is resolved on demand via npx (npm exec)."
pause "Ready to check the repo state?"

# ── Stage 2: Cloudflare credentials ──────────────────────────────────────
stage "Cloudflare credentials"
say "The trial needs a short-lived, scoped API token and your account id."
say "Both land in $ENV_FILE only — the script guards that file below."
if ! grep -qE '^\.env\.live-trial$' .gitignore 2>/dev/null; then
  printf '%s\n' ".env.live-trial" >> .gitignore
  say "added .env.live-trial to .gitignore so the token can never be committed."
fi
open_url "https://dash.cloudflare.com"
step "Pick your account: the account id is the hex string in the URL"
step "(/<ACCOUNT_ID>/...) and on the right of the overview page."
ask CF_ACCOUNT_ID "Paste the account id:"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → use the 'Edit Cloudflare Workers' template, then add"
step "Edit permission for D1, R2, Queues, Workflows, Secrets Store and"
step "Cron Triggers (deploy-button.md lists the mapping; src/lib/scopes.ts"
step "enumerates the abstract set the trial checks against)."
step "Set a short expiry (a day), create it, and copy the token once."
ask_secret CF_API_TOKEN "Paste the scoped API token (hidden):"
write_env CF_API_TOKEN "$CF_API_TOKEN"
warn "This token can edit workers and storage: it is revoked at stage 9."

# ── Stage 3: deploy ──────────────────────────────────────────────────────
stage "Deploy"
say "Building and deploying the worker to your account."
say "Deploy-button alternative: https://deploy.workers.cloudflare.com/?url=https://github.com/belikh/surveyor"
say "then continue here once the install redirects to the wizard."
if confirm "Run npm ci, build, and wrangler deploy now"; then
  npm ci
  npm run build
  export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN"
  say "wrangler refuses the placeholder D1 id, so the database is created"
  say "(or found by name) and its real id is written into wrangler.toml."
  say "A backup is taken first and restored at stage 10: the real id must"
  say "never be committed."
  INFO_OUT=""
  LIST_OUT=""
  DB_ID=""
  say "creating the D1 database (wrangler prints its id; an existing name falls back to lookup):"
  CREATE_OUT="$(wr d1 create surveyor-db 2>&1 || true)"
  DB_ID="$(printf '%s' "$CREATE_OUT" | grep -oE 'database_id = "[0-9a-f-]+"' | head -n1 | cut -d'"' -f2 || true)"
  if [[ -z "$DB_ID" ]]; then
    say "reading its id by name (d1 info, then d1 list):"
    INFO_OUT="$(wr d1 info surveyor-db --json 2>&1 || true)"
    DB_ID="$(printf '%s' "$INFO_OUT" | parse_uuid || true)"
  fi
  if [[ -z "$DB_ID" ]]; then
    LIST_OUT="$(wr d1 list --json 2>&1 || true)"
    DB_ID="$(printf '%s' "$LIST_OUT" | parse_uuid || true)"
  fi
  if [[ -z "$DB_ID" ]]; then
    warn "could not resolve the D1 id. Raw outputs for diagnosis:"
    printf '%s\n' "--- create:" "$CREATE_OUT" "--- info:" "$INFO_OUT" "--- list:" "$LIST_OUT"
    warn "paste the above back for a fix, and record it in the findings file."
    exit 1
  fi
  cp wrangler.toml /tmp/surveyor-wrangler.toml.bak
  sed -i "s/database_id = \"REPLACE_VIA_PROVISIONING\"/database_id = \"$DB_ID\"/" wrangler.toml
  # R2 buckets are not auto-provisioned by deploy (queues are): create the
  # corpus bucket or confirm it exists before deploying.
  say "creating the R2 bucket (or confirming it exists):"
  R2_OUT=""
  if ! wr r2 bucket list 2>/dev/null | grep -q "surveyor-corpus"; then
    R2_OUT="$(wr r2 bucket create surveyor-corpus 2>&1 || true)"
  fi
  if ! wr r2 bucket list 2>/dev/null | grep -q "surveyor-corpus"; then
    warn "the surveyor-corpus bucket is missing."
    if printf '%s' "$R2_OUT" | grep -q "10042\|enable R2"; then
      say "R2 is not enabled on this Cloudflare account yet — enabling it is"
      say "a dashboard step this wizard cannot take for you:"
      open_url "https://dash.cloudflare.com"
      step "Open R2 in the sidebar and follow the enable flow (it may ask"
      step "for billing details), then re-run this wizard; everything saved"
      step "so far is remembered."
    else
      warn "the create output was:"
      printf '%s\n' "$R2_OUT"
    fi
    warn "record it in the findings file."
    exit 1
  fi
  wr deploy
  unset CLOUDFLARE_API_TOKEN
fi
say "The worker URL looks like https://surveyor.<you>.workers.dev"
ask WORKER_URL "Paste the deployed worker URL (no trailing slash):"
write_env WORKER_URL "$WORKER_URL"

# ── Stage 4: boot ────────────────────────────────────────────────────────
stage "Boot the installation"
open_url "$WORKER_URL"
step "The boot panel asks for a Cloudflare token, account id and script"
step "name: reuse the stage-2 token, $CF_ACCOUNT_ID, and 'surveyor'."
step "Choose the operator token in YOUR PASSWORD MANAGER now — generate a"
step "fresh one. The wizard never asks for it here and never saves it:"
step "the installation never returns it, and the receipt carries slot names"
step "and booleans only (A1)."
step "Press 'Boot installation'."
pause "Booted (the wizard moved past the boot panel)?"

# ── Stage 5: OAuth consent round trip ────────────────────────────────────
stage "OAuth consent round trip (PKCE, live)"
say "This is the one-click path the product is designed around (ADR-0008,"
say "ADR-0013): consent replaces the pasted token entirely. It needs one"
say "registered OAuth client first — a two-minute dashboard step, verified"
say "against the Cloudflare docs:"
open_url "https://dash.cloudflare.com"
step "Select your account → Manage Account → OAuth clients → Create client."
step "Client name anything (e.g. surveyor-wizard); response type 'code';"
step "grant type 'authorization_code'; token endpoint auth method 'none'"
step "(PKCE public client — no secret is created or sent, per ADR-0013)."
step "Redirect URI, exactly:"
step "  $WORKER_URL/api/oauth/callback"
step "Choose scopes covering Workers Scripts write and account read, create,"
step "and copy the client id. Private visibility is fine (your members only;"
step "no domain verification needed for this trial)."
ask CF_OAUTH_CLIENT_ID "Paste the OAuth client id (or empty to skip the consent leg):"
if [[ -z "$CF_OAUTH_CLIENT_ID" ]]; then
  warn "no client id: the consent leg cannot be exercised this run."
  say "Record this in the findings file at stage 8."
else
  say "Setting CF_OAUTH_CLIENT_ID as a public var and redeploying:"
  # Idempotent across re-runs: replaces the empty default or a previous id.
  sed -i "s/^CF_OAUTH_CLIENT_ID = \".*\"$/CF_OAUTH_CLIENT_ID = \"$CF_OAUTH_CLIENT_ID\"/" wrangler.toml
  export CLOUDFLARE_API_TOKEN="$CF_API_TOKEN"
  wr deploy
  unset CLOUDFLARE_API_TOKEN
  open_url "$WORKER_URL"
  step "Providers panel → 'Connect Cloudflare' → consent at Cloudflare."
  step "Confirm the panel reads 'Cloudflare connected. The token is held in"
  step "this tab and never stored.' — that is the PKCE round trip working live."
  pause "Consent completed and the panel shows connected?"
fi

# ── Stage 6: provisioner and scope mapping ──────────────────────────────
stage "Provisioner and scope mapping"
say "The operator token gates /api/provision. It is typed, never saved:"
ask_secret OPERATOR_TOKEN "Paste the operator token from stage 4 (hidden, not saved):"
say "Running POST /api/provision with the transient stage-2 token."
say "Expected: ok:true with a receipt of slot names and booleans only —"
say "no secret value anywhere in the receipt, log or response."
RECEIPT_JSON="$EVIDENCE_DIR/$TRIAL_DATE-provision-receipt.json"
# The token travels in a temp body file, never in the curl argv (ps-visible).
BODY_JSON="$(mktemp)"
WIZ_CF_TOKEN="$CF_API_TOKEN" WIZ_CF_ACCOUNT="$CF_ACCOUNT_ID" node -e 'const fs=require("fs");fs.writeFileSync(process.argv[1],JSON.stringify({cf_token:process.env.WIZ_CF_TOKEN,account_id:process.env.WIZ_CF_ACCOUNT,script_name:"surveyor"}))' "$BODY_JSON"
if curl -sS -X POST "$WORKER_URL/api/provision" \
  -H "authorization: Bearer $OPERATOR_TOKEN" \
  -H 'content-type: application/json' \
  -d "@$BODY_JSON" \
  -o "$RECEIPT_JSON" -w 'HTTP %{http_code}\n'; then
  say "receipt saved to $RECEIPT_JSON (safe to commit: no values by design)."
else
  warn "provision call failed — record the step and message in the findings file."
fi
rm -f "$BODY_JSON"
unset OPERATOR_TOKEN
step "Scope check: open src/lib/scopes.ts REQUIRED_SCOPES and confirm each"
step "abstract scope (workers/d1/r2/queues/workflows/secrets/triggers write)"
step "was covered by the token you created. Any 502 permission step names"
step "the scope that was missing — that is a finding, not a failure of the trial."
pause "Receipt reviewed and scope mapping noted?"

# ── Stage 7: deployed smoke, browser path, Workers AI lanes ─────────────
stage "Deployed smoke and live lanes (A17)"
say "HTTP surface plus the at-rest ciphertext audit against the live build."
say "Run this yourself (your terminal, your token — it is never saved here):"
say ""
say "  node scripts/smoke.mjs \"$WORKER_URL\" --token <operator-token>"
say ""
pause "Smoke run finished? Note any failing check for the findings file."
step "Browser PDF path: open $WORKER_URL/survey in a real browser, submit"
step "with a scanned-page upload if you have one, and confirm extraction and"
step "rasterisation run in the page as shipped (served pdf worker asset)."
step "Workers AI lanes: in the operator UI upload a scan and POST"
step "/api/corpus/drain — a transcribed/OCRed verdict proves the AI binding;"
step "a held status naming the missing capability proves the honest fallback."
step "With a BYOK provider key, add it in the wizard and re-drain to see the"
step "registry lanes take over."
pause "Smoke, browser path and lane behaviour recorded in your notes?"

# ── Stage 8: findings ────────────────────────────────────────────────────
stage "Findings"
say "Appending the trial record template (fill in defects before closing):"
if [[ ! -f "$EVIDENCE_FILE" ]]; then
  cat > "$EVIDENCE_FILE" <<EOF
# Live provisioning trial — $TRIAL_DATE

Worker: $WORKER_URL
Issues: A16 #17 (provisioner + consent, scope mapping), A17 #18 (deployed smoke, browser path, Workers AI lanes).

## Scope mapping

| Abstract scope (src/lib/scopes.ts) | Granted on the token | Observed working live |
|---|---|---|
| workers:write | | |
| d1:write | | |
| r2:write | | |
| queues:write | | |
| workflows:write | | |
| secrets:write | | |
| triggers:write | | |

## Steps run

- [ ] Boot via the wizard boot panel (A1 path)
- [ ] OAuth consent round trip (or: no client id — registration unverified)
- [ ] POST /api/provision receipt (see $TRIAL_DATE-provision-receipt.json)
- [ ] scripts/smoke.mjs against the live URL
- [ ] Browser PDF extraction + rasterisation in a real browser
- [ ] Workers AI lane drain (or honest held fallback)
- [ ] Teardown via the wizard + resource delete + token revoked

## Defects found (fixed or filed)

1.

## Verdict for #17 / #18

EOF
  say "created $EVIDENCE_FILE"
fi
say "Open $EVIDENCE_FILE in your editor and fill the tables now."
say "When done, comment the findings (and link the evidence) on"
say "https://github.com/belikh/surveyor/issues/17 and /18."
pause "Findings recorded?"

# ── Stage 9: teardown ────────────────────────────────────────────────────
stage "Teardown (irreversible)"
open_url "$WORKER_URL"
step "Teardown screen → 'Connect Cloudflare' if asked → the teardown button."
step "Confirm the 'Teardown complete' receipt: it names exactly what was"
step "wiped and what was not (account logs/analytics are outside control)."
if confirm "The wizard reported teardown complete"; then
  say "ok"
else
  warn "stop and record the failure in the findings file before continuing."
  exit 1
fi
step "In the dashboard (Workers & Pages, D1, R2, Queues) confirm the"
step "trial resources are gone; delete by hand anything the receipt missed."
open_url "https://dash.cloudflare.com"
pause "Dashboard confirms nothing trial-owned remains?"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Revoke the stage-2 API token now (Roll/Delete on its row)."
if confirm "Token revoked"; then
  say "blast radius closed."
else
  warn "revoke it before you close this terminal."
fi

# ── Stage 10: scrub and close ────────────────────────────────────────────
stage "Scrub and close"
if [[ -f "$ENV_FILE" ]]; then
  if command -v shred >/dev/null 2>&1; then shred -u "$ENV_FILE"; else rm -f "$ENV_FILE"; fi
  say "session file removed."
fi
if [[ -f /tmp/surveyor-wrangler.toml.bak ]]; then
  cp /tmp/surveyor-wrangler.toml.bak wrangler.toml
  rm -f /tmp/surveyor-wrangler.toml.bak
  say "wrangler.toml restored to the committed placeholder (real D1 id kept out of git)."
fi
say "Committable artefacts (receipts carry no secret values by design):"
say "  $EVIDENCE_FILE"
say "  $EVIDENCE_DIR/$TRIAL_DATE-provision-receipt.json"
say "Then comment findings on #17 and #18."
# ──────────────────────────────────────────────────────────────────────────

finish
