#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from the repository root so `gh` targets the right repository.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TOTAL_STAGES=6

banner "Niro · DeepSeek BYOK setup"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "This wizard wires DeepSeek into the Niro find workflow."
say "It sets one GitHub secret and three repository variables; nothing local."
printf '\n'
say "Repository: $(git remote get-url origin 2>/dev/null || echo 'no origin remote')"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh: authenticated as $(gh api user --jq .login 2>/dev/null || echo 'unknown')"
else
  warn "gh is missing or not authenticated."
  warn "The wizard will still capture values, but you must set them by hand after."
fi
pause "Press Enter to start."

# ── Stage 2: DeepSeek API key ─────────────────────────────────────────────
stage "DeepSeek: API key"
say "Create an API key and store it as the CI secret COPILOT_PROVIDER_API_KEY."
open_url "https://platform.deepseek.com/api_keys"
step "Sign in to the DeepSeek platform (register first if you have no account)."
step "Open 'API keys' and create a new key; name it something like 'niro-ci'."
step "Copy the key (the platform shows it when it is created)."
ask_secret COPILOT_PROVIDER_API_KEY "Paste the DeepSeek API key:"
if [[ -z "${COPILOT_PROVIDER_API_KEY:-}" ]]; then
  warn "No key entered. Re-run this wizard once you have one."
  exit 1
fi
set_secret COPILOT_PROVIDER_API_KEY "$COPILOT_PROVIDER_API_KEY"

# ── Stage 3: verify the key ───────────────────────────────────────────────
stage "Verify the key"
say "Checking the key against DeepSeek before it goes anywhere near CI."
if ! command -v curl >/dev/null 2>&1; then
  warn "curl is not installed, so the live check is skipped."
elif models=$(curl -fsS --max-time 20 https://api.deepseek.com/models \
    -H "Authorization: Bearer $COPILOT_PROVIDER_API_KEY" 2>/dev/null); then
  if printf '%s' "$models" | grep -q '"deepseek-flash"'; then
    say "Key works; deepseek-flash is available."
  else
    warn "The key works, but 'deepseek-flash' was not in the model list."
    note "Models seen: $(printf '%s' "$models" | grep -o '"id": *"[^"]*"' | head -c 300)"
    confirm "Store this key anyway?" || exit 1
  fi
else
  warn "The check failed: bad key, no network, or a rate limit."
  if ! confirm "Store this key anyway?"; then exit 1; fi
fi

# ── Stage 4: endpoint and dialect ─────────────────────────────────────────
stage "Endpoint and dialect"
say "These are public and go in as repository variables."
note "DeepSeek is OpenAI-compatible; its documented base URL is below."
ask COPILOT_PROVIDER_BASE_URL "DeepSeek base URL [https://api.deepseek.com]:"
COPILOT_PROVIDER_BASE_URL="${COPILOT_PROVIDER_BASE_URL:-https://api.deepseek.com}"
ask COPILOT_PROVIDER_TYPE "Provider type [openai]:"
COPILOT_PROVIDER_TYPE="${COPILOT_PROVIDER_TYPE:-openai}"
set_var COPILOT_PROVIDER_BASE_URL "$COPILOT_PROVIDER_BASE_URL"
set_var COPILOT_PROVIDER_TYPE "$COPILOT_PROVIDER_TYPE"

# ── Stage 5: model ────────────────────────────────────────────────────────
stage "Model"
say "The Copilot BYOK provider serves a single model."
note "Niro uses this model for every task tier that niro/niro.yaml does not pin."
note "Documented ids: deepseek-flash (V4.1 Flash, default), deepseek-v4-pro."
ask COPILOT_MODEL "Model id [deepseek-flash]:"
COPILOT_MODEL="${COPILOT_MODEL:-deepseek-flash}"
set_var COPILOT_MODEL "$COPILOT_MODEL"

# ── Stage 6: verify wiring ────────────────────────────────────────────────
stage "Verify wiring"
say "What GitHub now holds for the Niro workflow:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  printf '\n'
  gh secret list | grep -E '^COPILOT_PROVIDER_API_KEY' || warn "secret not listed yet"
  gh variable list | grep -E '^COPILOT_(PROVIDER_(BASE_URL|TYPE)|MODEL)' || warn "variables not listed yet"
  printf '\n'
else
  warn "gh not ready; set these by hand:"
  note "gh secret set COPILOT_PROVIDER_API_KEY"
  note "gh variable set COPILOT_PROVIDER_BASE_URL --body 'https://api.deepseek.com'"
  note "gh variable set COPILOT_PROVIDER_TYPE --body 'openai'"
  note "gh variable set COPILOT_MODEL --body 'deepseek-flash'"
fi
say "Dispatch the assessment (workflow must be on the default branch):"
note "gh workflow run niro-find.yml -f agent=copilot -f goal='Test the survey submission flow'"
pause "Press Enter to finish."

finish
